services:
  - type: web
    name: seizure-prediction-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: seizure-prediction-db
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true

  - type: pserv
    name: seizure-prediction-db
    env: postgresql
    plan: free
    ipAllowList: []